### ISSUE TITLE
Cluster API Add-on Provider for Helm (CAAPH) integration

### ISSUE THREAD

**Issue by Preisschild** [Jont828/cluster-api-visualizer#41]
Hi

Currently, the CAPI Visualizer just shows ClusterResourceSet Addons.
I think integrating with [CAAPH](https://github.com/kubernetes-sigs/cluster-api-addon-provider-helm) and showing their resources (`HelmChartProxy`&`HelmChartRelease`) would be a good addition.

**Comment by Jont828** [comment]
@Preisschild This is something I would like to add as well. It's a similar use case to #42 as the issue is this app uses the clusterctl client to fetch the resources and CAAPH is not included in the clusterctl discovery. This is b/c it'd be a circular dependency since CAAPH imports CAPI, so we'd need a workaround to list external CRDs. One solution I was thinking of would be to add a label to other CRD types and query those instead.

**Comment by Jont828** [comment]
Should be done with #43!
