### ISSUE TITLE
Helm chart should always return latest image

### ISSUE THREAD

**Issue by fabriziopandini** [Jont828/cluster-api-visualizer#6]
Currently when using this from CAPI we are pinning to a specific image tag, and this will require some maintenance to keep up with new releases.
Instead, we would like the helm chart to always return the latest image by default

**Comment by Jont828** [comment]
Sure, I think we can set it up so the Helm chart references the `latest` tag instead of a specific version. The only thing is that older versions of the Helm chart might not work with the latest Docker image, i.e. the older versions don't have a ClusterRoleBinding in the chart. Is there a best practice for how to deal with that? Or would it be easier for our purposes to maintain a rolling version of the chart?

**Comment by fabriziopandini** [comment]
Could it be possible for CAPI to get always the latest version of the chart?
If this is possible, then it doesn't matter if a specific version of the chart is pinned to an image version or if it uses `:latest` tag.
What is important from my PoV is that the version pinning does not happen in CAPI because most of the maintainers don't have visibility into the visualizer release cadence

**Comment by Jont828** [comment]
Yes, that should be possible. If you do helm install without a version it will fetch the latest chart from the repo. If I remove the image tag from values.yaml and instead put it in the chart, I believe fetching the latest chart will then include the latest Docker image. The only thing is for CAPI, do we need to manually delete `hack/observability/visualizer/charts` for it to pull the latest version?

**Comment by Jont828** [comment]
It seems like we are just pinning the version in CAPI now.
